mininglee/ideal-happiness

- 김우섭 장바구니 html
> Update 김우섭 장바구니 html

- 안서영 free01.html
free01이 마지막 수정본이니까 free01로 봐주시면 되겠습니다.
> Create 안서영 free01.html

- 김우섭 장바구니 css
> Update 김우섭 장바구니 css

- 박경호 count&size html
// 반려동물 수, 사이즈 버튼 클릭시 나타나는 페이지
> Create 박경호 count&size.html

- 박경호 calendar.html
> Create 박경호 calendar.html

- 박경호 kind.html
> Create 박경호 kind.html

- 안서영 event.html 버튼 추가
> Create 안서영 event.html 글쓰기 버튼 추가

- 안서영 event.css 수정
> Create 안서영 event.css 수정

- 안서영 free01.css 글쓰기 버튼 추가
> Create 안서영 free01.css 글쓰기 버튼 추가

- 안서영 free01.html 글쓰기 버튼 추가
> Create 안서영 free01.html 글쓰기 버튼 추가

- 안서영 friends.css 글쓰기 버튼 추가
> Create 안서영 friends.css 글쓰기 버튼 추가

- 안서영 friends.html 글쓰기 버튼 추가
> Create 안서영 friends.html 글쓰기 버튼 추가

- 안서영 product.html 글쓰기 버튼 추가
> Create 안서영 product.html 글쓰기 버튼 추가

- 안서영 product.css 글쓰기 버튼 추가
> Create 안서영 product.css 글쓰기 버튼 추가

- 김우섭 CSS
> Update 김우섭 CSS

- 김우섭 HTML
2023.06.29
이미지 메인페이지와 동일하게 변경 및 크기 조정
상품목록 배치 오류 수정 및 여백 조정
> Update 김우섭 HTML

- sql 김우섭
> Update sql 김우섭

- sql 김태인
> Update sql 김태인

- model2 + jsp 수정본(박경호)
> Create model2 + jsp 수정본(박경호)

- SQL 재정리
int 에 , 하나 빠진거 수정했습니다 . 그리고 몇개 오류 나는거 있는데 상관없을듯 합니다
> Update SQL 재정리

- Active 김태인
Map 패키지 만들어서 그 안에 넣어 주세요:: 김태인
> Create Active 김태인

- mapDao 김태인
> Create mapDao.java 김태인

- ApiController.java 김태인
> Create ApiController.java 김태인

- member - MemberDao.java
main - java - member - MemberDao.java
> Create member - MemberDao.java

- member - MemberMybatis.java
main - java - member - MemberMybatis.java
> Create member - MemberMybatis.java

- mybatis - MemberAnno.java
main - java - mybatis - MemberAnno.java
> Create mybatis - MemberAnno.java

- memberDeleteForm.jsp(최종본) - 박경호
webapp - view - member - memberDeleteForm.jsp
> Create memberDeleteForm.jsp(최종본) - 박경호

- memberPassForm.jsp(최종본) - 박경호
webapp - view - member - memberPassForm.jsp
> Create memberPassForm.jsp(최종본) - 박경호

- memberUpdateForm.jsp(최종본) - 박경호
webapp - view - member - memberUpdateForm.jsp
> Create memberUpdateForm.jsp(최종본) - 박경호

- myinfo.jsp(최종본) - 박경호
webapp - view - member - myinfo.jsp
> Create myinfo.jsp(최종본) - 박경호

- myinfoPro.jsp(최종본) - 박경호
webapp - view - member - myinfoPro.jsp
> Create myinfoPro.jsp(최종본) - 박경호

- Ani.java
main - java - animal - Ani.java
> Create Ani.java(최종본) - 박경호

- AniGroup.java(최종본) - 박경호
main - java - animal - AniGroup.java
> Create AniGroup.java(최종본) - 박경호

- AniMybatis.java
main - java - animal - AniMybatis.java
> Create AniMybatis.java(최종본) - 박경호

- AniAnno.java(최종본) - 박경호
main - java - mybatis - AniAnno.java
> Create AniAnno.java(최종본) - 박경호

- LoginUser.java(최종본) - 박경호
main - java - login - LoginUser.java
> Create LoginUser.java(최종본) - 박경호

- 게시판 table
> Create 게시판 table
